stf/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *


urlpatterns = [
    path('',              home,               name="home"),
    path('blog/',     blog,                   name="blog" ),
    path('contact/',        contact,          name="contact"),
    path('carrer/',     carrer,               name="carrer"),
    path('job/<int:pk>/', job_view,           name="job_view"),
    path('resume/',         resume,                  name="resume"     ),
    # path('logout/' ,      logout_view,           name="logout" ),
    # path('state_city/' ,  state_city,            name="state_city"  ),
    # path('inactive-user/',inactive_user  ,       name="inactive-user"),
    # path("profile-save/", complete_profile_save, name="profile-save"),
    # path('category/',     category,              name="category"     ),
   
]

tayyab/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stf.urls')),
    path('',include('users.urls') ),
    path('social-auth/',include('social_django.urls',namespace='social')),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stf/models.py
from django.db import models
from django.utils import timezone

from tinymce.models import HTMLField
from tinymce import widgets as tinymce_widgets
class Course(models.Model):
    name=models.CharField(max_length=80)
    description=HTMLField()
    image=models.ImageField(upload_to="CourseImages")

    def __str__(self):
        return self.name

class Services(models.Model):
    name=models.CharField(max_length=80)
    description=HTMLField()

    def __str__(self):
        return self.name



class Blog(models.Model):
    title=models.CharField(max_length=80)
    description=HTMLField()
    blog_publish = models.DateTimeField(default=timezone.now)
    image=models.ImageField(upload_to="BlogImages")

    def __str__(self):
        return self.title

class Career(models.Model):
    job_title=models.CharField(max_length=80)
    job_description=HTMLField()
    job_experience=models.CharField(max_length=80,blank=True,null=True)
    job_publish = models.DateTimeField(default=timezone.now)
    location=models.CharField(max_length=200)
    Qualification=models.CharField(max_length=100)
    Department=models.CharField(max_length=100)

    job_type=models.CharField(max_length=80,default="Full Time")
    No_of_openings=models.CharField(max_length=80,default="1")
    
    #resume=models.FileField(upload_to="CareerResume" ,blank=True, null=True)

    def __str__(self):
        return self.job_title


class JobSeeker(models.Model):
    Name=models.CharField(max_length=80)
    Email = models.CharField(max_length=100)
    Mobile=models.CharField(max_length=200)
    resume=models.FileField(upload_to="CareerResume")
    Apply_at = models.DateTimeField(null=True,blank=True,default=timezone.now)

    def __str__(self):
        return self.Name

stf/forms.py
from django import forms

from .models import *

class ResumeForm(forms.ModelForm):
    class Meta:
        model=JobSeeker
        fields=['Name','Email','Mobile','resume']

stf/views.py
from django.shortcuts import render,redirect
from stf.models import *
from stf.forms import *
from django.core.mail import send_mail
from datetime import date, timedelta,datetime
from time import gmtime, strftime
from django.contrib import messages
showtime = strftime("%H:%M:%S")
def home(request):
    #alll coure
    alls=Course.objects.all()
    #all services
    all_services=Services.objects.all()

    context={
        'couses':alls,
        'services':all_services,
    }

    return render(request, 'main/home.html',context)


def blog(request):
    blogs=Blog.objects.all()
    return render(request, 'blogs/blog.html',{'blogs':blogs}) 
    

def carrer(request):
    careers=Career.objects.all()
    return render(request, 'career/career.html',{'careers':careers}) 

def job_view(request ,pk):
    get_job=Career.objects.get(id=pk)
    context={'get_job':get_job,
            'form':ResumeForm()
                
    }
    return render(request, 'career/job_view.html',context)     





def contact(request):
    print(request)
    if request.GET:
        
        message_name=request.GET.get('message_name')
        meassage_email= request.GET.get('meassage_email')
        fullmessage=request.GET.get('message')
        
        
        send_mail(
			message_name, 
			fullmessage,
           
			'mawazid1051@gmail.com',
			[meassage_email],
			fail_silently=False,

        )
        
        return redirect('home')
    return redirect('home')


def resume(request):
    if request.method == 'POST':
        print("this is post request")
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request , 'Your request is submitted successfully')
            return redirect('carrer')
    return redirect('carrer')

stf/templates/career/career.html
{% extends 'main/base.html' %}

{% load static %}
{% block header %}



<header class="header">

  <div id="menu-btn" class="fas fa-bars"></div>

  <a href="{% url 'home' %}" class="logo"> <span>StoXx</span>ZoOm</a>

  <nav class="navbar">
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'home' %}">services</a>
      <a href="{% url 'home' %}">Courses</a>
     
      <a href="{% url 'home' %}">contact</a>
     
      <a href="{% url 'blog' %}">Blogs</a>
      <a href="{% url 'carrer' %}">Careers</a>
      
  </nav>
  
  
  {% if user.is_authenticated %}
  <div id="login-btn">
  <a class="btn" href="">{{request.user}}</a>
  <a class="btn"href="/logout">Logout</a> 
  
  <a href="/logout"><i class="fas fa-sign-out-alt"></i></a>
   </div>
  {% else %}
  <div id="login-btn">
    <a href="/login"> <button class="btn">login</button></a>
   
    <a href="/login"><i class="far fa-user"></i></a>
</div>
  {% endif %}

</header> 

{% endblock header %} 


{% block content %}





<link rel="stylesheet" href="{% static  'frontend/career/css/styles.css' %}">
<section class="card container grid">
  <div class="card__container grid">
      <!--==================== CARD 1 ====================-->
      {% for career in careers %}
      <article class="card__content grid">
      
          <header class="card__header">
              <!-- <div class="card__header-circle grid">
                  <img src="assets/img/free-coin.png" alt="" class="card__header-img">
              </div> -->
              
              <span class="card__header-subtitle">{{career.job_publish}}</span>
              <h1 class="card__header-title">{{career.job_title}}</h1>
          </header>
          
          <ul class="card__list grid">
              <li class="card__list-item">
                  <i class="uil uil-check card__list-icon"></i>
                  <p class="card__list-description"><i class="fas fa-clock"></i>  {{career.job_experience}} years experience</p>
              </li>
              <li class="card__list-item">
                  <i class="uil uil-check card__list-icon"></i>
                  <p class="card__list-description"><i class="far fa-hand-point-right"></i> {{career.job_type}}</p>
              </li>
              <li class="card__list-item">
                  <i class="uil uil-check card__list-icon"></i>
                  <p class="card__list-description"><i class="fas fa-graduation-cap"></i>  {{career.Qualification}}</p>
              </li>
              <li class="card__list-item">
                  <i class="uil uil-check card__list-icon"></i>
                  <p class="card__list-description"><i class="fas fa-map-marker-alt"></i> {{career.location}}</p>
              </li>
          </ul>
            <a href="{% url 'job_view' career.id %}"><button class="card__button">Check</button></a>
          
      </article>

      <!--==================== CARD 2 ====================-->
     {% endfor %}
  </div>
</section>



{% endblock content %}

stf/templates/career/job_view.html
{% extends 'main/base.html' %}

{% load static %}
{% block header %}

<header class="header">

  <div id="menu-btn" class="fas fa-bars"></div>

  <a href="{% url 'home' %}" class="logo"> <span>StoXx</span>ZoOm</a>

  <nav class="navbar">
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'home' %}">services</a>
      <a href="{% url 'home' %}">Courses</a>
     
      <a href="{% url 'home' %}">contact</a>
     
      <a href="{% url 'blog' %}">Blogs</a>
      <a href="{% url 'carrer' %}">Careers</a>
      
  </nav>
  
  
  {% if user.is_authenticated %}
  <div id="login-btn">
  <a class="btn" href="">{{request.user}}</a>
  <a class="btn"href="/logout">Logout</a> 
  
  <a href="/logout"><i class="fas fa-sign-out-alt"></i></a>
   </div>
  {% else %}
  <div id="login-btn">
    <a href="/login"> <button class="btn">login</button></a>
   
    <a href="/login"><i class="far fa-user"></i></a>
</div>
  {% endif %}

</header> 

{% endblock header %} 




{% block content %}
<!--============  Success Mesaage ========-->

<!--============End  Success Mesaage ========-->
<style>
    .home{
      background-color:  #4070F4;
    }
  .home .home-slider .slide{
      display: flex;
      align-items: center;
      flex-wrap: wrap;
      gap:2rem; 
      padding-top: 2rem;
  }
  
  .home .home-slider .slide .content{
      flex:1 1 45rem;
  }
  
  .home .home-slider .slide .image{
      flex:1 1 45rem;
  }
  
  .home .home-slider .slide .image img{
      width: 100%;
  }
  
  .home .home-slider .slide .content span{
      color:var(--green);
      font-size: 2.5rem;
      font-weight:bold;
      color:white;
  }
  
  
  
  .home .home-slider .slide .content p{
      color:var(--light-color);
      font-size: 2.2rem;
      padding:.5rem 0;
      line-height: 1.5;
      color:white;
  }
  
  </style>
    <section class="home" id="home">
  
      <div class="swiper-container home-slider">
  
          <div class="swiper-wrapper wrapper">
  
              <div class="swiper-slide slide">
                  <div class="content">
                      
                      
                      <p>{{get_job.job_title}}</p>
                      <span>Full Time</span>
                  </div>
                  
              </div>
  
           
  
          </div>
  
         
  
      </div>
  
  </section>
<section class="icons-container">

    <div class="icons">
        <i class="fas fa-home"></i>
        <div class="content">
            <h3>Job Experience</h3>
            <p>{{get_job.job_experience}}</p>
        </div>
    </div>

    <div class="icons">
        <i class="fas fa-graduation-cap"></i>
        <div class="content">
            <h3>Qualifications</h3>
            <p>{{get_job.Qualification}}</p>
        </div>
    </div>

    <div class="icons">
        <i class="fas fa-users"></i>
        <div class="content">
            <h3>Department</h3>
            <p>{{get_job.Department}}</p>
        </div>
    </div>

    <div class="icons">
        <i class="fas fa-list-ol"></i>
        <div class="content">
            <h3>No. of Openings</h3>
            <p>{{get_job.No_of_openings}}</p>
        </div>
    </div>

</section>
    <style>
        .content_text {
            width: 95vw;
            margin: 20px;
            font-size: 16px;
            padding:10px 5px 5px 5px ;
            display:flex;
 
    font-size: 1.5vw; 
}

    </style>


<style>

  
    .about .row{
        display: flex;
        flex-wrap: wrap;
        gap:1.5rem;
        align-items: center;
       
    }
    
    .about .row .image{
        flex:1 1 45rem;
    }
    
    .about .row .image img{ 
        width: 100%;
    }
    
    .about .row .content{
        flex:1 1 45rem;
    }
    
    .about .row .content h3{
        color: #4070F4;
        font-size: 4rem;
        padding:.5rem 0;
    }
    
    .about .row .content p{
        color:var(--light-color);
        font-size: 1.5rem;
        padding:.5rem 0;
        line-height: 2;
    }
    
    .about .row .content .icons-container{
        display: flex;
        gap:1rem;
        flex-wrap: wrap;
        padding:1rem 0;
        margin-top: .5rem;
    }
    
    .about .row .content .icons-container .icons{
        background:#eee;
        border-radius: .5rem;
        border:.1rem solid rgba(0,0,0,.2);
        display: flex;
        align-items: center;
        justify-content: center;
        gap:1rem;
        flex:1 1 17rem;
        padding:1.5rem 1rem;
    }
    
    .about .row .content .icons-container .icons i{
        font-size: 2.5rem;
        color:var(--green);
    }
    
    .about .row .content .icons-container .icons span{
        font-size: 1.5rem;
        color:var(--black);
    }
    form #id_Name ,#id_Email ,#id_Mobile ,#id_resume{
    width:100%;
    border-radius: .7rem;
    padding:1rem 1.2rem;
    font-size: 1.6rem;
    text-transform: none;
    border:2px solid #4070F4;
    margin:.7rem 0;
}
form label {
font-size:16px;
}
    </style>


<section class="about" id="about">
   
    <div class="row">
        <div class="content">
            <h3>Job description</h3>
            <p>{{get_job.job_description}}</p> 
        </div>
        <div class="image">
            <form action="{% url 'resume' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}
<!--                  
                  <input type="text" name="Name" placeholder="your name" class="box">
                  <input type="email" name="Email" placeholder="your email" class="box">
                  <input type="text" name="Mobile" placeholder="mobile number" class="box">
                  <input type="file" name="resume" placeholder="your email" class="box">
                   -->
                  <input type="submit" value="send message" class="btn">
              </form>

              
        </div>
  
       
  
    </div>
  

  
  </section>
{% endblock %}